name: Build TWRP for Motorola Fogos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11' # You can change this version if needed

    - name: Set up repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=$PATH:~/bin' >> $GITHUB_ENV

    - name: Initialize repo
      run: |
        repo init -u https://github.com/LineageOS/android.git -b lineage-18.1
        repo sync -j4

    - name: Clone the TWRP device tree for Moto G 5G (fogos)
      run: |
        git clone https://github.com/your-username/twrp_device_motorola_fogos.git device/motorola/fogos

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        lunch twrp_fogos-eng
        make -j4
